// hooks/useRegister.ts
import { useState } from 'react';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { auth } from '@/lib/api/firebase/init';
import CompanyModel from '@/models/company';
import { createCompany } from '@/lib/api/user/company-service';
import { createApplicant } from '@/lib/api/user/applicant-service';

interface RegisterProps {
    email: string;
    password: string;
    company?: Omit<CompanyModel, "id" | "uid">; // Exclude id and uid as they will be generated by Firebase
    applicant?: any;
}

interface RegisterHook {
    register: (props: RegisterProps) => Promise<any>;
    isLoading: boolean;
    error: string | null;
}

export const useRegister = (): RegisterHook => {
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const register = async ({ email, password, company, applicant }: RegisterProps) => {
        setIsLoading(true);
        setError(null);

        let returnData = null;

        try {
            const user = await createUserWithEmailAndPassword(auth, email, password);

            // Here you would typically save the user data to your database
            if (company) {
                returnData = await createCompany({ ...company, uid: user.user.uid });
            }
            if (applicant) {
                returnData = await createApplicant({ ...applicant, uid: user.user.uid });
            }

        } catch (err) {
            let errorMessage = 'Registration failed. Please try again.';

            if (err instanceof Error) {
                switch (err.message) {
                    case 'Firebase: Error (auth/email-already-in-use).':
                        errorMessage = 'Email is already in use.';
                        break;
                    case 'Firebase: Error (auth/invalid-email).':
                        errorMessage = 'Invalid email address.';
                        break;
                    case 'Firebase: Error (auth/weak-password).':
                        errorMessage = 'Password should be at least 6 characters.';
                        break;
                }
            }

            setError(errorMessage);
        } finally {
            setIsLoading(false);
        }

        return returnData;
    };

    return { register, isLoading, error };
};